// CMD
DEF_ASM_TOK(HLT,  CMD, 0)
DEF_ASM_TOK(PUSH, CMD, 1)
DEF_ASM_TOK(POP,  CMD, 1)
DEF_ASM_TOK(ADD,  CMD, 0)
DEF_ASM_TOK(SUB,  CMD, 0)
DEF_ASM_TOK(MUL,  CMD, 0)
DEF_ASM_TOK(DIV,  CMD, 0)
DEF_ASM_TOK(IN,   CMD, 0)
DEF_ASM_TOK(OUT,  CMD, 0)
DEF_ASM_TOK(RET,  CMD, 0)

// JMP
DEF_ASM_TOK(JMP,  JUMP, 1)
DEF_ASM_TOK(JE,   JUMP, 1)
DEF_ASM_TOK(JNE,  JUMP, 1)
DEF_ASM_TOK(JG,   JUMP, 1)
DEF_ASM_TOK(JL,   JUMP, 1)
DEF_ASM_TOK(CALL, JUMP, 1)
